spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/booking
    username: postgres
    password: 4444

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: main

logging:
  level:
    lab.booking: INFO
